[project]
name = "smollm"
version = "0.1.0"
description = "SmolLM series tuning notebooks"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "transformers>=4.54.1",
    "datasets>=4.0.0",
    "trl>=0.2.0",
    "peft>=0.16.0",
    "torch"
]
